apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-es
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: fluentd-es
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
