apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-logging
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: {{ .Values.kibana-replicaCount }}
  selector:
    matchLabels:
      k8s-app: kibana-logging
  template:
    metadata:
      labels:
        k8s-app: kibana-logging
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: kibana-logging
        image: docker.elastic.co/kibana/kibana-oss:6.2.4
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: {{ .Values.kibana-service.resources.limits.cpu }}
          requests:
            cpu: {{ .Values.kibana-service.resources.requests.cpu }}
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch-logging:9200
        ports:
        - containerPort: {{ .Values.kibana-service.port }}
          name: {{ .Values.kibana-service.targetPort }}
          protocol: {{ .Values.kibana-service.protocol }}
