apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        env:
          - name: DB_DRIVER
            value: pgsql
          - name: DB_HOST
            value: {{ template "postgresql.fullname" . }}
          - name: DB_DATABASE
            value: {{ .Values.postgresql.postgresDatabase }}
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            valueFrom: { secretKeyRef:    { name: {{ template "postgresql.fullname" . }}, key: postgres-password } }
          - name: SESSION_DRIVER
            value: database
          - name: CACHE_DRIVER
            value: database
          - name: APP_URL
            value: {{ .Values.appUrl }}
          - name: MAIL_HOST
            value: {{ .Values.mailHost }}
          - name: MAIL_PORT
            value: {{ default "25" .Values.mailPort | quote }}
          - name: MAIL_ADDRESS
            value: {{ default "noreply@example.com" .Values.mailSenderEmail | quote }}
          - name: MAIL_NAME
            value: {{ default "Status" .Values.mailSenderName | quote }}

