{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  {{- if .Values.ingress.tlsCertificate }}
  tls:
    - secretName: {{ .Release.Name }}
      hosts:
{{ toYaml .Values.ingress.hosts | indent 8}}
  {{- end }}
  rules:
{{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $.Release.Name }}
            servicePort: {{ $.Values.service.externalPort }}
{{- end }}
{{- end }}
