apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
type: Opaque
data:
{{- if .Values.ingress.tlsCertificate }}
  tls.crt: {{ .Values.ingress.tlsCertificate | b64enc }}
  tls.key: {{ .Values.ingress.tlsKey | b64enc }}
{{- end }}
