# Default values for cachet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: cachethq/docker
  tag: latest
service:
  name: cachet
  type: ClusterIP
  externalPort: 80
  internalPort: 80

postgresql:
  postgresDatabase: postgres

ingress:
  enabled: false
  hosts: []
#  tlsCertificate:
#  tlsKey:

appUrl: https://status.example.com
mailSenderEmail: noreply@example.com
